// Authentication Routes
export const AuthRoutes = {
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/login",
  REGISTER: "/register",
};

// Authenticated Routes
export const AuthenticatedRoutes = {
  USER_HOME: "/",
  USER_DASHBOARD: "/dashboard",
  USER_PROFILE: "/profile",
  BANK_DETAILS: "/bank-details",
  PACKAGE_REPORT: "/package-report",
  // SELF_INCOME_REPORT: "/self-income-report",
  REFERRAL_INCOME_REPORT: "/referral-income-report",
  NEWS_AND_NOTIF: "/news-and-notif",
  SPIN_INCOME_REPORT: "/spin-income-report",
  LEVEL_INCOME_REPORT: "/levelIncome-history",
  MATCHING_INCOME_REPORT: "/matching-income-report",
  ROI_INCOME_HISTORY: "/roi-history",
  ROYALTY_INCOME_REPORT: "/royalty-income-report",
  FUND_TRANSFER: "/fund-transfer",
  FUND_REQUEST: "/fund-request",
  FUND_REQUEST_HISTORY: "/fund-request-history",
  FUND_TRANSFER_HISTORY: "/fund-transfer-history",
  FUND_RECEIVE_HISTORY: "/fund-receive-history",
  TEAM_DIRECT: "/team-direct",
  TEAM_TREE: "/team-tree",
  WALLET: "/wallet",
  WITHDRAWAL_REPORT: "/withdrawal-report",
  OUR_PLANS: "/our-plans",
  ADMIN_DASHBOARD: "/admin-dashboard",
  PENDING_USERS: "/pending-users",
  PENDING_FUND_REQUEST: "/pending-fund-request",
  PENDING_WITHDRAWAL_REQUEST: "/pending-withdrawal-request",
  APPROVED_USERS: "/approved-users",
  APPROVED_FUND_REQUEST: "/approved-fund-request",
  APPROVED_WITHDRAWAL_REQUEST: "/approved-withdrawal-request",
  REJECTED_USERS: "/rejected-users",
  REJECTED_FUND_REQUEST: "/rejected-fund-request",
  REJECTED_WITHDRAWAL_REQUEST: "/rejected-withdrawal-request",
  SUPPORT_RAISE_TICKET_HISTORY: "/support-raise-ticket-history",
  SUPPORT_RAISE_TICKET: "/support-raise-ticket",
  RAISE_TICKET_LIST: "/raise-ticket-list",
  ALL_USERS: "/all-users",
  PURCHASE_PLAN_HISTORY: "/purchase-plan-history",
  ROI_INCOME_REPORT: "/direct-referral-income-report",
  NEWS_AND_NOTIF_ADMIN: "/news-and-notif-admin",
  WITHDRAWAL_UPDATE: "/withdrawal-update",
  ACTIVE_USERS: "/active-users",
  DIRECT_REFERRAL_INCOME_REPORT: "/direct-referral-income-report",
  TRANSACTION_LIMIT: "/transaction-limit",
  MIN_MAX_LIMIT: "/min-max-limit",
  MIN_PACKAGE_AMOUNT: "/min-package-amount",
  EMAIL_REGISTRATION: "/email-registration",
  WITHDRAWAL_BLOCK: "/withdrawal-block",
  USER_TRANSACTION_LIMIT: "/user-transaction-limit",
};
